### ISSUE TITLE
404

### ISSUE THREAD

**Issue by VEBERArnaud** [eleven-labs/eleven-labs.github.io#109]
BESOIN FONCTIONNEL
-------------------------------
 - Quel est le besoin ?

Avoir une page 404 qui ne ressemble pas à rien.
pour l'instant elle à cette tête là: https://eleven-labs.github.io/fr/toto/

 - Comment valider ?

La page 404 ne doit pas ressembler à rien

SPECIFICATION TECHNIQUE
------------------------------------------
Modifier la page : https://github.com/eleven-labs/eleven-labs.github.io/blob/master/404.md

**Comment by MaxLf** [comment]
Pour info sur le site on a celle là, qui est quand même stylée : http://eleven-labs.com/toto

**Comment by snroki** [comment]
azy je regarde :)
