### ISSUE TITLE
Passer le site en HTTPS ou HTTP2

### ISSUE THREAD

**Issue by ulrik59** [eleven-labs/eleven-labs.github.io#142]
BESOIN FONCTIONNEL
-------------------------------
 - Il faut passer le site en full HTTPS ou HTTP2 pour des raisons de sécurité et de bonne pratique mais aussi par rapport à Google, il me semble que Google, au niveau du référencement, a tendance à délaisser voire ignorer les sites qui ne sont pas HTTPS

SPECIFICATION TECHNIQUE
------------------------------------------
Le fait que github pages ne soit en HTTPS ou HTTP2 lorsque l'on utilise un domain custom est une difficulté supplémentaire mais on peut utiliser les pistes présentes dans ce lien :
https://www.jonathan-petitcolas.com/2017/01/13/using-https-with-custom-domain-name-on-github-pages.html

**Comment by VEBERArnaud** [comment]
Pour l'instant c'est compliqué avec github pages de mettre en place https et/ou http2

**Comment by VEBERArnaud** [comment]
mais il n'est pas certains que l'on reste sur github pages

une solution CloudFront -> S3 -> jekyll buildé a été évoqué. affaire à suivre
