### ISSUE TITLE
Limiter le nombre des derniers articles

### ISSUE THREAD

**Issue by Pouzor** [eleven-labs/eleven-labs.github.io#144]
BESOIN FONCTIONNEL
-------------------------------
 - Quel est le besoin ?
  Dans la page author, changer l'intitulé "derniers articles" en "Mes articles" 
  Ex : http://blog.eleven-labs.com/authors/captainjojo
 - Comment valider ?
Voir "Mes articles"

SPECIFICATION TECHNIQUE
------------------------------------------

Changer l'intitulé sur la page auteur

**Comment by CaptainJojo** [comment]
changer l'intitulé c'est pas mal.=> les articles de l'auteurs

**Comment by Pouzor** [comment]
Du coup @ElevenTom  tu confirme ? "les articles de l'auteurs"

**Comment by ElevenTom** [comment]
Sans la faute pourquoi pas. 
Mais à la limite je préférerais "Derniers articles de l'auteur" ou peut-être même mieux "Du même auteur".
