### ISSUE TITLE
Automatiser la vérification orthographique

### ISSUE THREAD

**Issue by ulrik59** [eleven-labs/eleven-labs.github.io#163]
Afin de s'assurer de la qualité orthographique et grammaticale des articles, on pourrait mettre en place une vérification orthographique automatisé via par exemple un [Travis](https://travis-ci.org/).
On pourrait pour cela utiliser [Aspell](https://doc.ubuntu-fr.org/aspell) ou équivalent.
Il serait important que cette vérification n'empêche pas le merge mais soit seulement informative, du fait des nombreux faux-positif que l'on peut avoir avec le jargon technique, notamment en français.

**Comment by ElevenTom** [comment]
Ah oui ça pourrait être pas mal, surtout pour les fautes d'accents et de lettres oubliées ou en double ! :p

**Comment by VEBERArnaud** [comment]
on pourrait peut être utilisé un service SaaS pour ça

**Comment by ch3ric** [comment]
Done in this PR: https://github.com/eleven-labs/eleven-labs.github.io/pull/196

**Comment by VEBERArnaud** [comment]
@ulrik59, on peut close cette issue du coup ?
