### ISSUE TITLE
"A Lire aussi"

### ISSUE THREAD

**Issue by BenAmarEleven** [eleven-labs/eleven-labs.github.io#165]
BESOIN FONCTIONNEL
-------------------------------
 - Quel est le besoin ?
Pourquoi à la fin d'un article dans le "A Lire aussi" on me propose en premier l'article que je viens de lire?

![image](https://user-images.githubusercontent.com/12557457/28372575-5ef08c88-6ca0-11e7-8fd3-c5a42d0c6444.png)

 - Comment valider ?

SPECIFICATION TECHNIQUE
------------------------------------------
*A définir par les développeurs*

**Comment by CaptainJojo** [comment]
Done par @snroki
