### ISSUE TITLE
Avoir un lien pour pouvoir naviguer vers le site Corporate Eleven Labs depuis le blog Eleven

### ISSUE THREAD

**Issue by ElevenFranck** [eleven-labs/eleven-labs.github.io#167]
BESOIN FONCTIONNEL
-------------------------------
 - Quel est le besoin ?

Pouvoir naviguer entre le blog et le site Eleven Labs facilement. 

solution proposée : Ajouter un lien vers le site Corporate  sur le logo Eleven Labs en haut à gauche du blog. 

SPECIFICATION TECHNIQUE
------------------------------------------
*A définir par les développeurs*

**Comment by snroki** [comment]
+1 @ElsaEleven faut pas changer le lien sur le logo, par contre on peut très bien rajouter un lien en haut à droite, faut juste définir l'icône à utiliser !

**Comment by ElevenTom** [comment]
Une fusée ? :p

**Comment by ElevenTom** [comment]
J'ai une idée ! En gros :

1/ On rajoute un bouton home (logo de maison) en haut et au centre. Ça me semble le plus instinctif pour retourner sur la page d'accueil.
2/ Le clic sur le Logo Eleven Labs ne nous emmène non plus sur la home, mais sur le site (ce qui me semble plus logique). En plus de ça on rajoute la mention "le site" sur l'image pour clarifier (voir ci-dessous)
![logo eleven labs le site](https://user-images.githubusercontent.com/16896128/28784065-958dcc9e-7612-11e7-9585-1b6665917495.png)

**Comment by VEBERArnaud** [comment]
c'est toujours aussi confusant
pourquoi ne pas ajouter tout simplement un lien vers le site ?

**Comment by VEBERArnaud** [comment]
pour moi faut faire [ca](https://github.com/eleven-labs/eleven-labs.github.io/issues/167#issuecomment-316631871)

**Comment by ElevenTom** [comment]
Donc dans ce cas on fout un vrai bouton "home" en haut à gauche ! 
Et on utilise le logo avec "Eleven Labs : Le site" en haut à droite ?
