### ISSUE TITLE
Optimisation des assets

### ISSUE THREAD

**Issue by ulrik59** [eleven-labs/eleven-labs.github.io#169]
Il serait intéressant de pouvoir minifier JS, CSS et optimiser les images et SVG.
Cela pourrait se faire à priori via un plugin Jekyll.

**Comment by VEBERArnaud** [comment]
il est de toute façon prévu qu'une liste de bonnes pratiques sur les images soit mise en place

on peut effectivement l'étendre aux css & js, voir l'automatiser par un plugin
