### ISSUE TITLE
Mettre à jour l'image sur la cover du blog

### ISSUE THREAD

**Issue by ElevenTom** [eleven-labs/eleven-labs.github.io#173]
BESOIN FONCTIONNEL
-------------------------------
 - Quel est le besoin ?
Mettre à jour l'image sur la cover du blog, pour que figure la mention "Blog"
 - Comment valider ?
Lorsque l'image sur la cover correspondra à l'image en PJ :p 
(N.B. : L'image est blanche et c'est un png, donc on voit rien sur l'aperçu, il faut l'ouvrir)
SPECIFICATION TECHNIQUE
------------------------------------------
*A définir par les développeurs*
![logo blanc 350 dpi le blog](https://user-images.githubusercontent.com/16896128/28408620-5b1d797a-6d38-11e7-844e-fc6c4131d547.png)

**Comment by VEBERArnaud** [comment]
je m'en charge
