### ISSUE TITLE
[feat] Importer les images

### ISSUE THREAD

**Issue by CaptainJojo** [eleven-labs/eleven-labs.github.io#19]
# Description

Récupérer l'ensemble des images du blog eleven

**Comment by guillemcanal** [comment]
Bloqué par #38 

Dès que nous aurons chacun des articles en `*.md`, nous pourrons:

- Collecter les liens images dans les articles
- Les télécharger dans un répertoire `assets` (arborescence du répertoire image a décider ensemble, car ça risque d'être un gros bordel si tout les fichiers sont à la racine du répertoire des assets)
- Modifier les `*.md` pour modifier les liens vers les images (https://jekyllrb.com/docs/posts/#including-images-and-resources)

**Comment by VEBERArnaud** [comment]
je pensais a un dossier par article.

`assets/<article1>/<image1>`
`assets/<article1>/<image2>`
`assets/<article2>/<image3>`

vous en pensez quoi ?
