### ISSUE TITLE
Problème de textes en français quand article en anglais

### ISSUE THREAD

**Issue by ElevenTom** [eleven-labs/eleven-labs.github.io#199]
BESOIN FONCTIONNEL
-------------------------------
 - Quel est le besoin ?
Certains textes ne sont pas traduits automatiquement lorsqu'un article est publié en anglais.
Notamment : 
-Le "Par" qui annonce l'auteur de l'article (qui devrait être "by")
-Le "lecture" qui annonce le temps de lecture (qui pourrait être "x min read" comme dans medium)

Voir imp ecran (merci @elfakamal, qui a remarqué tout ça ;))

 - Comment valider ?

SPECIFICATION TECHNIQUE
------------------------------------------
*A définir par les développeurs*

<img width="1074" alt="screen shot 2017-08-16 at 11 08 52" src="https://user-images.githubusercontent.com/16896128/29357052-811b7a66-8276-11e7-8fda-026961b646fe.png">

**Comment by ch3ric** [comment]
This issue is a duplicate of this one: https://github.com/eleven-labs/eleven-labs.github.io/issues/26
