### ISSUE TITLE
[feat] Configurer Google analytics

### ISSUE THREAD

**Issue by CaptainJojo** [eleven-labs/eleven-labs.github.io#22]
# Description

Avoir la même précision que wordpress pour l'analytics google

**Comment by VEBERArnaud** [comment]
Ajouter l'id google analytics ici: https://github.com/eleven-labs/eleven-labs.github.io/blob/master/_config.yml#L59

**Comment by CaptainJojo** [comment]
Done il ne manque plus qu'a donner les acces au personnes :)
