### ISSUE TITLE
bug - Affichage de la date invalide lors d'une recherche

### ISSUE THREAD

**Issue by lepiaf** [eleven-labs/eleven-labs.github.io#238]
Description:
- Affichage de la date invalide lors d'une recherche d'un article

Etapes:
- aller sur https://blog.eleven-labs.com/
- cliquer sur "search"
- taper "symfony"

Actuel:
- la date affiché sous le titre de l'article est "Invalid date"

Attendu:
- la date affiché sous le titre de l'article doit être celui de l'article

**Comment by lepiaf** [comment]
je pense qu'algolia ne renvoi pas la date dans les résultats

https://github.com/eleven-labs/eleven-labs.github.io/blob/cf572061744d48dc0f0212c2b7b588c21498ffe1/js/search.js#L36

**Comment by lepiaf** [comment]
firefox il ne comprend pas

```new Date("2011-11-01 00:00:00 +0000")```

mais

```new Date("2011-11-01 00:00:00+0000")```

**Comment by lepiaf** [comment]
la solution serait de mettre la date correctement formaté dans algolia

**Comment by ulrik59** [comment]
@lepiaf Le bug est censé être corrigé, tu confirmes ?

**Comment by lepiaf** [comment]
it works :+1:
