### ISSUE TITLE
[feat] Mettre en place Discuss 

### ISSUE THREAD

**Issue by CaptainJojo** [eleven-labs/eleven-labs.github.io#25]
# Description 

Mettre en place Discuss et faire en sorte que chaque personne reçoivent les notifications sur son article

**Comment by CaptainJojo** [comment]
@VEBERArnaud il faudra mettre cela sur une compte eleven dédié :)

**Comment by VEBERArnaud** [comment]
@captainjojo, yes pour l'instant c'est mon mail eleven, faudra créer un compte avec celui de wilson
