### ISSUE TITLE
[feat] Mettre en place un moteur de recherche

### ISSUE THREAD

**Issue by CaptainJojo** [eleven-labs/eleven-labs.github.io#30]
## Description

Dans la cadre de la suppression des catégories, il serait mieux d'avoir un moteur de recherche disponible sur toute les pages.

## Spécification fonctionnelle

La recherche s'effectue sur le titre et le contenu.

**Comment by VEBERArnaud** [comment]
Algolia a fait un plugin jekyll pour ca:
https://github.com/algolia/algoliasearch-jekyll

**Comment by guillemcanal** [comment]
Suggestion : 

- Si la recherche s'effectue sur le titre des contenus, pas besoin d'Algolia pour ça : https://lunrjs.com/
- Si on souhaite recherche dans les contenus tout en gardant la main sur l'infra
    - @eko peut jeter un oeil sur http://www.blevesearch.com/ (Go) pas besoin de persister l'index dans le filesystem, il peut être maintenu en mémoire, donc un binaire à héberger sur une petite instance et basta
   - Sinon il reste l'option ElasticSearch :3
