### ISSUE TITLE
[Bonus][feat] Provide a Docker image

### ISSUE THREAD

**Issue by guillemcanal** [eleven-labs/eleven-labs.github.io#39]
Provide a Docker image to allow contributor to run Jekyll with ease.

See if https://hub.docker.com/r/jekyll/jekyll/ is a good feat.

**Comment by snroki** [comment]
Is it really useful ? You just need to run this command : 
`docker run --rm --label=jekyll --volume=$(pwd):/srv/jekyll \
  -it -p 127.0.0.1:4000:4000 jekyll/jekyll jekyll serve
`
Maybe a simple Makefile will do the job no ?

**Comment by guillemcanal** [comment]
Nope it won't do :

1. Won't work on Windows (Docker for Windows and Docker Machine)

2. This will make Jekyll rebuild its dependencies everytime the command is
invoked (ruby gems).

Moreover, If you wish to check if a named container is already running to
prevent rebuild, it is really painfull to do with bash.

docker-compose is the way to go IMO.


Le 17 mai 2017 10:22, "snroki" <notifications@github.com> a écrit :

Is it really useful ? You just need to run this command :

Maybe a simple Makefile will do the job no ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/eleven-labs/eleven-labs.github.io/issues/39#issuecomment-302020943>,
or mute the thread

**Comment by ulrik59** [comment]
@guillemcanal There is now a `docker-compose.yml` in the project. Is this issue fixed for you ?

**Comment by guillemcanal** [comment]
@ulrik59 yup my dear.
