### ISSUE TITLE
Afficher les articles en AMP

### ISSUE THREAD

**Issue by VEBERArnaud** [eleven-labs/eleven-labs.github.io#50]
BESOIN FONCTIONNEL
-------------------------------
 - Quel est le besoin ?

Pour chaque article avec une version AMP

 - Comment valider ?

Chaque article à une version .amp

SPECIFICATION TECHNIQUE
------------------------------------------

Suivre les reco AMP disponible ici https://www.ampproject.org/fr/

**Comment by VEBERArnaud** [comment]
on peut jeter un oeil a ce plugin, ca à l'air de faire le taff 
https://github.com/juusaw/amp-jekyll

**Comment by CaptainJojo** [comment]
j'aime beaucoup l'idée

**Comment by ulrik59** [comment]
@VEBERArnaud Est-ce totalement fait ? On pourrait fermer l'issue si c'est le cas

**Comment by VEBERArnaud** [comment]
c'est @CaptainJojo qui s'en est occuper mais il me semble que tout est ok cote amp

**Comment by VEBERArnaud** [comment]
je close au pire on re-ouvrira
