### ISSUE TITLE
Multiple auteurs

### ISSUE THREAD

**Issue by snroki** [eleven-labs/eleven-labs.github.io#91]
BESOIN FONCTIONNEL
-------------------------------
 - Quel est le besoin ?

Pouvoir afficher plusieurs auteurs pour un article

 - Comment valider ?

Voir plusieurs auteurs pour un article

SPECIFICATION TECHNIQUE
------------------------------------------

J'ai vu plusieurs solutions :
http://www.codingpedia.org/ama/how-to-handle-multiple-authors-in-jekyll/
https://stackoverflow.com/questions/15189008/how-can-i-have-multiple-authors-for-one-post-in-jekyll
https://gist.github.com/ravasthi/1834570

En gros c'est pas trop dur, faut juste définir comment on utilise le champ author dans nos posts et après modifier le template

Vous en pensez quoi ?

Ex : https://eleven-labs.github.io/fr/retour-symfony-live-paris-2017/ on est 2 à avoir écrit l'article et aucun auteur ne s'affiche

**Comment by CaptainJojo** [comment]
ce que propose https://stackoverflow.com/questions/15189008/how-can-i-have-multiple-authors-for-one-post-in-jekyll me parait parfait :)

**Comment by VEBERArnaud** [comment]
ca a cassé la liste des articles pour un auteur

**Comment by CaptainJojo** [comment]
il est dessus :)

**Comment by snroki** [comment]
Cey bon :)
